---
name: actions-release-ui-components
description: |
  Releases the UI Components package to NPM and GitHub.
inputs:
  UPDATE_DOWNSTREAM_REPOS:
    description: Whether to trigger the Nebula UI and Prefect OSS NPM package updates.
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Test
      run: |
        if ${{ inputs.UPDATE_DOWNSTREAM_REPOS == 'true' }}
        then
          echo "Hello I have been triggered because this has been set to true"
        fi
      shell: bash
