---
name: actions-release-ui-components
description: |
  Releases the UI Components package to NPM and GitHub.
inputs:
  UPDATE_DOWNSTREAM_REPOS:
    description: Whether to trigger the Nebula UI and Prefect OSS NPM package updates.
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Test
      if: |
        ${{ inputs.UPDATE_DOWNSTREAM_REPOS == 'true' }}
      run: |
        echo "Hello I have been triggered because this has been set to true"
      shell: bash
    - name: Another Test
      if: |
        ${{ inputs.UPDATE_DOWNSTREAM_REPOS == 'false' }}
      run: |
        echo "Hello I have not been triggered because this has been set to false"