---
name: actions-release-ui-components
description: |
  Releases the UI Components package to NPM and GitHub.
inputs:
  NPM_TOKEN:
    description: The NPM token to use for publishing the package.
    required: true
  GITHUB_TOKEN:
    description: The Github token to use for creating the release.
    required: true
  NEBULA_UI_ACTIONS_RW_TOKEN:
    description: The Github token to use for triggering the Nebula UI NPM package update.
    required: false
  PREFECT_OSS_ACTIONS_RW_TOKEN:
    description: The Github token to use for triggering the Prefect OSS NPM package update.
    required: false
  UPDATE_DOWNSTREAM_REPOS:
    description: Whether to trigger the Nebula UI and Prefect OSS NPM package updates.
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"

    - name: Install Dependencies
      run: npm ci
      shell: bash

    - name: Build Package
      run: npm run build
      shell: bash

    - name: Trigger Nebula UI NPM Package Update
      # if: |
      #   ${{ inputs.UPDATE_DOWNSTREAM_REPOS == 'true' }} && ${{ steps.publish.outputs.type }}
      env:
        GITHUB_TOKEN: ${{ inputs.NEBULA_UI_ACTIONS_RW_TOKEN }}
        tag: "2.0.2"
      run: |
        gh workflow run npm_update_latest_prefect.yaml \
            --repo=prefecthq/nebula-ui \
            --ref=main \
            -f package_name="$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" \
            -f package_version="$tag"
      shell: bash

    # - name: Publish Package to NPM
    #   id: publish
    #   uses: JS-DevTools/npm-publish@v2
    #   with:
    #     token: ${{ inputs.NPM_TOKEN }}
    #     strategy: upgrade
    #     access: public

    # - name: Create Release
    #   if: ${{ steps.publish.outputs.type }}
    #   env:
    #     GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    #     tag: ${{ steps.publish.outputs.version }}
    #   run: |
    #     gh release create "$tag" \
    #         --repo="$GITHUB_REPOSITORY" \
    #         --title="Release ${tag#v}" \
    #         --generate-notes
    #   shell: bash

    # - name: Trigger Nebula UI NPM Package Update
    #   if: |
    #     ${{ inputs.UPDATE_DOWNSTREAM_REPOS == 'true' }} && ${{ steps.publish.outputs.type }}
    #   env:
    #     GITHUB_TOKEN: ${{ inputs.NEBULA_UI_ACTIONS_RW_TOKEN }}
    #     tag: ${{ steps.publish.outputs.version }}
    #   run: |
    #     gh workflow run npm_update_latest_prefect.yaml \
    #         --repo=prefecthq/nebula-ui \
    #         --ref=main \
    #         -f package_name="$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" \
    #         -f package_version="$tag"
    #   shell: bash

    # - name: Trigger Prefect OSS NPM Package Update
    #   if: |
    #     ${{ inputs.UPDATE_DOWNSTREAM_REPOS == 'true' }} && ${{ steps.publish.outputs.type }}
    #   env:
    #     GITHUB_TOKEN: ${{ inputs.PREFECT_OSS_ACTIONS_RW_TOKEN }}
    #     tag: ${{ steps.publish.outputs.version }}
    #   run: |
    #     gh workflow run npm_update_latest_prefect.yaml \
    #         --repo=prefecthq/prefect \
    #         --ref=main \
    #         -f package_name="$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" \
    #         -f package_version="$tag"
    #   shell: bash
